#include "cpptest.h"

#include "C:\Users\ruiking\Documents\Visual Studio 2010\Projects\Calculator\Calculator\Calculator.cpp"
#include "C:\Users\ruiking\Documents\Visual Studio 2010\Projects\Calculator\Calculator\tests\autogenerated\т╢нд╪Ч\TestSuite_Calculator_cpp.cpp"

